### ISSUE TITLE
Finding a suitable database and server

### ISSUE THREAD

**Issue by Irving-Hua** [yang242j/VSB_Plus#6]
backend

**Comment by yang242j** [comment]
AWS ec2: Need self organize, 1st year free (smallest)
Lightsail: Expensive, Instance ($3.5 USD/month, 1st month free), Database ($15 USD/month), Storage ($0.1 USD/GB/month)

**Comment by yang242j** [comment]
Final decision: 
AWS ec2 t2.medium
ip: 15.223.123.122
$0.0512 per On Demand Linux t2.medium Instance Hour
